<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://ros.org/wiki/xacro">
  
  <xacro:property name="radius" value="0.16"/> 
  <xacro:property name="height" value="0.10"/> 

  <material name="orange">
    <color rgba="1.0 0.5 0.0 1.0"/>
  </material>

  <material name="gray">
    <color rgba="0.6 0.6 0.6 1.0"/>
  </material>

  <link name="base_footprint">
    <!-- Virtual frame sitting on the ground to anchor base_link -->
  </link>

  <joint name="base_footprint_to_base_link" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/> 
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${radius}" length="${height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    
    <visual>
      <origin xyz="${radius * 0.85} 0 ${height}" rpy="0 0 0"/>
      <geometry>
        <box size="${2 * radius} 0.05 0.08"/> 
      </geometry>
      <material name="gray"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${radius}" length="${height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <mass value="4.0"/>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
</robot>
